#!/bin/sh

if [ -z $XDG_CURRENT_DESKTOP ]; then
    export XDG_CURRENT_DESKTOP="GNOME-Flashback:GNOME"
fi

gnome-session --help 2>/dev/null | grep -- --builtin > /dev/null
HASBUILTIN=$?
if [ $HASBUILTIN -eq 0 ]; then
    BUILTINARG="--builtin"
else
    BUILTINARG=""
fi

exec gnome-session $BUILTINARG --session=i3-gnome-flashback --disable-acceleration-check "$@"
